version: 2.1

aliases:
  - &working_directory  ~/chanakya
  - &load_node
    - image: circleci/node:10.16

  - &save-install-cache
    paths:
      - node_modules
    key: v1-install-{{ checksum "yarn.lock" }}
  - &restore-install-cache
    keys:
      - v1-install-{{ checksum "yarn.lock" }}
      - v1-install-

  - &persist_install_node
    root: *working_directory
    paths:
      - node_modules

  - &attach-install_node
    at: *working_directory

jobs:
  install:
    working_directory: *working_directory
    docker: 
      - image: *load_node
    steps:
      - checkout
      - restore_cache: *restore-install-cache
      - run: npm install
      - save_cache: *save-install-cache
      - persist_to_workspace: *persist_install_node
  lint:
    docker:
      - image: *load_node
    steps:
      - checkout
      - attach_workspace: *attach-install_node
      - run: npm run lint

workflows:
  version: 2
  build-test-deploy:
  jobs:
    - install
    - lint
      requires:
        - install